# Generated by Django 3.0.5 on 2021-11-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='document',
        ),
    ]
