# Generated by Django 3.0.5 on 2021-11-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_status_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='document_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
