# Generated by Django 3.0.5 on 2021-11-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_status_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_driver',
            name='driver_ic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
