# Generated by Django 3.0.5 on 2021-11-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211117_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='officername',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
