# Generated by Django 3.0.5 on 2021-12-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211201_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_driver',
            old_name='vaccination_status_driver',
            new_name='vaccination_status',
        ),
    ]
