# Generated by Django 3.0.5 on 2021-12-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211201_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='vaccination_status_passenger1',
            field=models.CharField(choices=[('Default', 'Default'), ('No Vaccinate', 'No Vaccinate'), ('First Dose', 'First Dose'), ('Second Dose (Partial)', 'Second Dose (Partial)'), ('Second Dose (Full)', 'Second Dose (Full)')], default='Default', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='vaccination_status_passenger2',
            field=models.CharField(choices=[('Default', 'Default'), ('No Vaccinate', 'No Vaccinate'), ('First Dose', 'First Dose'), ('Second Dose (Partial)', 'Second Dose (Partial)'), ('Second Dose (Full)', 'Second Dose (Full)')], default='Default', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='vaccination_status_passenger3',
            field=models.CharField(choices=[('Default', 'Default'), ('No Vaccinate', 'No Vaccinate'), ('First Dose', 'First Dose'), ('Second Dose (Partial)', 'Second Dose (Partial)'), ('Second Dose (Full)', 'Second Dose (Full)')], default='Default', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='vaccination_status_passenger4',
            field=models.CharField(choices=[('Default', 'Default'), ('No Vaccinate', 'No Vaccinate'), ('First Dose', 'First Dose'), ('Second Dose (Partial)', 'Second Dose (Partial)'), ('Second Dose (Full)', 'Second Dose (Full)')], default='Default', max_length=500, null=True),
        ),
    ]
