# Generated by Django 3.0.5 on 2021-12-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211201_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='roadblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_plate', models.CharField(max_length=30, null=True)),
                ('location_data', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
