# Generated by Django 3.0.5 on 2021-12-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_roadblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_driver',
            name='gender',
            field=models.CharField(choices=[('Gender', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], default='gender', max_length=500, null=True),
        ),
    ]
