# Generated by Django 3.0.5 on 2021-12-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_driver_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='destination_state',
            field=models.CharField(choices=[('Default', 'Default'), ('Johor', 'Johor'), ('Kedah', 'Kedah'), ('Kelantan', 'Kelantan'), ('Kuala Lumpur', 'Kuala Lumpur'), ('Labuan', 'Labuan'), ('Melaka', 'Melaka'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Pahang', 'Pahang'), ('Perak', 'Perak'), ('Perlis', 'Perlis'), ('Putrajaya', 'Putrajaya'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('Terengganu', 'Terengganu')], default='Default', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='origin_state',
            field=models.CharField(choices=[('Default', 'Default'), ('Johor', 'Johor'), ('Kedah', 'Kedah'), ('Kelantan', 'Kelantan'), ('Kuala Lumpur', 'Kuala Lumpur'), ('Labuan', 'Labuan'), ('Melaka', 'Melaka'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Pahang', 'Pahang'), ('Perak', 'Perak'), ('Perlis', 'Perlis'), ('Putrajaya', 'Putrajaya'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('Terengganu', 'Terengganu')], default='Default', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_arrive',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='destination',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='origin',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='user_driver',
            name='Address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
