# Generated by Django 3.0.5 on 2021-12-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211208_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_driver',
            name='location_data',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='roadblock',
            name='location_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
