# Generated by Django 3.0.5 on 2021-12-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211208_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_driver',
            name='location_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='roadblock',
            name='location_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_driver',
            name='Address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user_driver',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_driver',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='gender', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_driver',
            name='ic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_driver',
            name='vaccination_status',
            field=models.CharField(blank=True, choices=[('No Vaccinate', 'No Vaccinate'), ('First Dose', 'First Dose'), ('Second Dose (Partial)', 'Second Dose (Partial)'), ('Second Dose (Full)', 'Second Dose (Full)')], default='Default', max_length=500, null=True),
        ),
    ]
