# Generated by Django 3.0.5 on 2021-12-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211223_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_driver',
            name='location_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
