# Generated by Django 3.0.5 on 2021-12-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211223_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_driver',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='gender', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_driver',
            name='vaccination_status',
            field=models.CharField(blank=True, choices=[('Default', 'Default'), ('No Vaccinate', 'No Vaccinate'), ('First Dose', 'First Dose'), ('Second Dose (Partial)', 'Second Dose (Partial)'), ('Second Dose (Full)', 'Second Dose (Full)')], default='Default', max_length=500, null=True),
        ),
    ]
