# Generated by Django 3.0.5 on 2021-12-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211229_0230'),
        ('accounts', '0018_auto_20211224_2328'),
    ]

    operations = [
    ]
