# Generated by Django 3.0.5 on 2022-01-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20211230_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='application',
        ),
    ]
